package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Wednesday, November 6, 2019 7:31:26 AM BRT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
