# DO NOT EDIT THIS FILE!
#
# Python module HelloApp__POA generated by omniidl

import omniORB
omniORB.updateModule("HelloApp__POA")

# ** 1. Stub files contributing to this module
import Hello_idl

# ** 2. Sub-modules

# ** 3. End
