// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __Hello_hh__
#define __Hello_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_Hello
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_Hello
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_Hello
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE HelloApp

_CORBA_MODULE_BEG

#ifndef __HelloApp_mHello__
#define __HelloApp_mHello__
  class Hello;
  class _objref_Hello;
  class _impl_Hello;
  
  typedef _objref_Hello* Hello_ptr;
  typedef Hello_ptr HelloRef;

  class Hello_Helper {
  public:
    typedef Hello_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_Hello, Hello_Helper> Hello_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_Hello,Hello_Helper > Hello_out;

#endif

  // interface Hello
  class Hello {
  public:
    // Declarations for this interface type.
    typedef Hello_ptr _ptr_type;
    typedef Hello_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_Hello :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    char* sayHello();

    // Constructors
    inline _objref_Hello()  { _PR_setobj(0); }  // nil
    _objref_Hello(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_Hello();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_Hello(const _objref_Hello&);
    _objref_Hello& operator = (const _objref_Hello&);
    // not implemented

    friend class Hello;
  };

  class _pof_Hello : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_Hello() : _OMNI_NS(proxyObjectFactory)(Hello::_PD_repoId) {}
    virtual ~_pof_Hello();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_Hello :
    public virtual omniServant
  {
  public:
    virtual ~_impl_Hello();

    virtual char* sayHello() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_HelloApp
_CORBA_MODULE_BEG

  class Hello :
    public virtual HelloApp::_impl_Hello,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~Hello();

    inline ::HelloApp::Hello_ptr _this() {
      return (::HelloApp::Hello_ptr) _do_this(::HelloApp::Hello::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_HelloApp
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
HelloApp::Hello::_marshalObjRef(::HelloApp::Hello_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_Hello
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_Hello
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_Hello
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_Hello
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_Hello
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_Hello
#endif

#endif  // __Hello_hh__

